# Generated by Django 2.0.2 on 2019-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Get_5Days_WeatherData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_city_name', models.CharField(max_length=100, verbose_name='City:')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
            ],
        ),
        migrations.AlterModelTable(
            name='citydata',
            table='city_data',
        ),
    ]
